name: 'Validate master branch with Repolinter'

on:
  push:
    branches:
      - main

jobs:
  repolinter-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: 'Run Repolinter'
        uses: DSACMS/repolinter-actions@main
        with:
          output_type: issue
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}