name: Test Modified Repolinter

on:
  workflow_dispatch: {} 
  
jobs:
  repolint:
    runs-on: ubuntu-latest
    name: Run Modified Repolinter
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: DSACMS/repolinter-action@main
        with:
          output_type: 'issue'
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          base_branch: 'main'