name: Test Modified Repolinter

on:
  workflow_dispatch: {}
  
jobs:
  repolint:
    runs-on: ubuntu-latest
    name: Run Modified Repolinter
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      # Use your forked and modified version
      - uses: sachin-panayil/repolinter-action@main
        with:
          output_type: 'pull-request'
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: 'repolinter.json'
          base_branch: 'main'