name: Update Contributors Information

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - 'MAINTAINERS.md'  # Only trigger when relevant file changes

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better git operations

      - name: Update contributor list
        id: contrib_list
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          readme_path: MAINTAINERS.md
          use_username: false
          commit_message: "chore: update contributors information"

      - name: Get contributors count
        id: get_contributors
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_INFO=$(echo $GITHUB_REPOSITORY | tr '/' ' ')
          OWNER=$(echo $REPO_INFO | awk '{print $1}')
          REPO=$(echo $REPO_INFO | awk '{print $2}')
          
          # Using GitHub CLI for better error handling and rate limiting
          CONTRIBUTORS=$(gh api graphql -f query='
            query($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                collaborators { totalCount }
              }
            }
          ' -f owner="$OWNER" -f repo="$REPO" --jq '.data.repository.collaborators.totalCount')

      - name: Update MAINTAINERS.md
        run: |
          CONTRIBUTORS="${{ steps.get_contributors.outputs.contributors }}"

          # Update contributor count with more reliable perl replacement
          perl -i -pe 's/(<!--CONTRIBUTOR COUNT START-->).*?(<!--CONTRIBUTOR COUNT END-->)/$1 '"$CONTRIBUTORS"' $2/' MAINTAINERS.md
          
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add MAINTAINERS.md
          git commit -m "chore: update contributors count to $CONTRIBUTORS"
          git push